export enum AuthEvents {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  ROLE_MISMATCH = 'ROLE_MISMATCH',
  INVALID_TOKEN = 'INVALID_TOKEN',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  EXPIRED_TOKEN = 'EXPIRED_TOKEN',
}
